
services:
  db:
    image: mysql:8.0
    container_name: recordatorios_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reminder_app
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recordatorios_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=reminder_app
      - JWT_SECRET=super_secret_key_123
      - PORT=3000
    depends_on:
      - db
    networks:
      - default
      - vigicloud_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:3000
    container_name: recordatorios_frontend
    restart: always
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - default
      - vigicloud_net

volumes:
  db_data:

networks:
  vigicloud_net:
    external: true
